services:
  app:
    build: .
    environment:
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - API_KEY=${API_KEY}
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./trigger:/app/trigger
